export const masterYarnDatabase = [
  {
    "id": "RHSS-001",
    "sku": "RHSS-001",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Black",
    "color_name": "Black",
    "colorFamily": "Neutral",
    "hex": "#111111",
    "imageUrl": "https://via.placeholder.com/80/111111/FFFFFF?text=Black",
    "swatchImageUrl": "https://via.placeholder.com/80/111111/FFFFFF?text=Black",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-002",
    "sku": "RHSS-002",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "White",
    "color_name": "White",
    "colorFamily": "Neutral",
    "hex": "#FFFFFF",
    "imageUrl": "https://via.placeholder.com/80/FFFFFF/000000?text=White",
    "swatchImageUrl": "https://via.placeholder.com/80/FFFFFF/000000?text=White",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-003",
    "sku": "RHSS-003",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Aran",
    "color_name": "Aran",
    "colorFamily": "Neutral",
    "hex": "#F0E2C0",
    "imageUrl": "https://via.placeholder.com/80/F0E2C0/000000?text=Aran",
    "swatchImageUrl": "https://via.placeholder.com/80/F0E2C0/000000?text=Aran",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-004",
    "sku": "RHSS-004",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Soft White",
    "color_name": "Soft White",
    "colorFamily": "Neutral",
    "hex": "#FFF9EA",
    "imageUrl": "https://via.placeholder.com/80/FFF9EA/000000?text=Soft+White",
    "swatchImageUrl": "https://via.placeholder.com/80/FFF9EA/000000?text=Soft+White",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-005",
    "sku": "RHSS-005",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Light Gray",
    "color_name": "Light Gray",
    "colorFamily": "Gray",
    "hex": "#BFC3C7",
    "imageUrl": "https://via.placeholder.com/80/BFC3C7/000000?text=Light+Gray",
    "swatchImageUrl": "https://via.placeholder.com/80/BFC3C7/000000?text=Light+Gray",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-006",
    "sku": "RHSS-006",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Charcoal",
    "color_name": "Charcoal",
    "colorFamily": "Gray",
    "hex": "#4B4B4B",
    "imageUrl": "https://via.placeholder.com/80/4B4B4B/FFFFFF?text=Charcoal",
    "swatchImageUrl": "https://via.placeholder.com/80/4B4B4B/FFFFFF?text=Charcoal",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-007",
    "sku": "RHSS-007",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Cherry Red",
    "color_name": "Cherry Red",
    "colorFamily": "Red",
    "hex": "#C8102E",
    "imageUrl": "https://via.placeholder.com/80/C8102E/FFFFFF?text=Cherry",
    "swatchImageUrl": "https://via.placeholder.com/80/C8102E/FFFFFF?text=Cherry",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-008",
    "sku": "RHSS-008",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Hot Red",
    "color_name": "Hot Red",
    "colorFamily": "Red",
    "hex": "#E02020",
    "imageUrl": "https://via.placeholder.com/80/E02020/FFFFFF?text=Hot+Red",
    "swatchImageUrl": "https://via.placeholder.com/80/E02020/FFFFFF?text=Hot+Red",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-009",
    "sku": "RHSS-009",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Burgundy",
    "color_name": "Burgundy",
    "colorFamily": "Red",
    "hex": "#6E1423",
    "imageUrl": "https://via.placeholder.com/80/6E1423/FFFFFF?text=Burgundy",
    "swatchImageUrl": "https://via.placeholder.com/80/6E1423/FFFFFF?text=Burgundy",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-010",
    "sku": "RHSS-010",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Pretty 'n Pink",
    "color_name": "Pretty 'n Pink",
    "colorFamily": "Pink",
    "hex": "#F49AC2",
    "imageUrl": "https://via.placeholder.com/80/F49AC2/000000?text=Pink",
    "swatchImageUrl": "https://via.placeholder.com/80/F49AC2/000000?text=Pink",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-011",
    "sku": "RHSS-011",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Perfect Pink",
    "color_name": "Perfect Pink",
    "colorFamily": "Pink",
    "hex": "#F26AA5",
    "imageUrl": "https://via.placeholder.com/80/F26AA5/000000?text=Perfect+Pink",
    "swatchImageUrl": "https://via.placeholder.com/80/F26AA5/000000?text=Perfect+Pink",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-012",
    "sku": "RHSS-012",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Light Raspberry",
    "color_name": "Light Raspberry",
    "colorFamily": "Pink",
    "hex": "#C83F7C",
    "imageUrl": "https://via.placeholder.com/80/C83F7C/FFFFFF?text=Raspberry",
    "swatchImageUrl": "https://via.placeholder.com/80/C83F7C/FFFFFF?text=Raspberry",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-013",
    "sku": "RHSS-013",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Pumpkin",
    "color_name": "Pumpkin",
    "colorFamily": "Orange",
    "hex": "#F47A20",
    "imageUrl": "https://via.placeholder.com/80/F47A20/000000?text=Pumpkin",
    "swatchImageUrl": "https://via.placeholder.com/80/F47A20/000000?text=Pumpkin",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-014",
    "sku": "RHSS-014",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Bright Yellow",
    "color_name": "Bright Yellow",
    "colorFamily": "Yellow",
    "hex": "#FFD51E",
    "imageUrl": "https://via.placeholder.com/80/FFD51E/000000?text=Yellow",
    "swatchImageUrl": "https://via.placeholder.com/80/FFD51E/000000?text=Yellow",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-015",
    "sku": "RHSS-015",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Gold",
    "color_name": "Gold",
    "colorFamily": "Yellow",
    "hex": "#D9A21B",
    "imageUrl": "https://via.placeholder.com/80/D9A21B/000000?text=Gold",
    "swatchImageUrl": "https://via.placeholder.com/80/D9A21B/000000?text=Gold",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-016",
    "sku": "RHSS-016",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Spring Green",
    "color_name": "Spring Green",
    "colorFamily": "Green",
    "hex": "#69B240",
    "imageUrl": "https://via.placeholder.com/80/69B240/000000?text=Spring",
    "swatchImageUrl": "https://via.placeholder.com/80/69B240/000000?text=Spring",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-017",
    "sku": "RHSS-017",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Paddy Green",
    "color_name": "Paddy Green",
    "colorFamily": "Green",
    "hex": "#159447",
    "imageUrl": "https://via.placeholder.com/80/159447/FFFFFF?text=Paddy",
    "swatchImageUrl": "https://via.placeholder.com/80/159447/FFFFFF?text=Paddy",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-018",
    "sku": "RHSS-018",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Hunter Green",
    "color_name": "Hunter Green",
    "colorFamily": "Green",
    "hex": "#254734",
    "imageUrl": "https://via.placeholder.com/80/254734/FFFFFF?text=Hunter",
    "swatchImageUrl": "https://via.placeholder.com/80/254734/FFFFFF?text=Hunter",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-019",
    "sku": "RHSS-019",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Tea Leaf",
    "color_name": "Tea Leaf",
    "colorFamily": "Green",
    "hex": "#5F7F52",
    "imageUrl": "https://via.placeholder.com/80/5F7F52/FFFFFF?text=Tea+Leaf",
    "swatchImageUrl": "https://via.placeholder.com/80/5F7F52/FFFFFF?text=Tea+Leaf",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-020",
    "sku": "RHSS-020",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Turqua",
    "color_name": "Turqua",
    "colorFamily": "Blue",
    "hex": "#00A6B2",
    "imageUrl": "https://via.placeholder.com/80/00A6B2/FFFFFF?text=Turqua",
    "swatchImageUrl": "https://via.placeholder.com/80/00A6B2/FFFFFF?text=Turqua",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-021",
    "sku": "RHSS-021",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Real Teal",
    "color_name": "Real Teal",
    "colorFamily": "Blue",
    "hex": "#007D83",
    "imageUrl": "https://via.placeholder.com/80/007D83/FFFFFF?text=Teal",
    "swatchImageUrl": "https://via.placeholder.com/80/007D83/FFFFFF?text=Teal",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-022",
    "sku": "RHSS-022",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Light Blue",
    "color_name": "Light Blue",
    "colorFamily": "Blue",
    "hex": "#8EC5E8",
    "imageUrl": "https://via.placeholder.com/80/8EC5E8/000000?text=Light+Blue",
    "swatchImageUrl": "https://via.placeholder.com/80/8EC5E8/000000?text=Light+Blue",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-023",
    "sku": "RHSS-023",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Blue",
    "color_name": "Blue",
    "colorFamily": "Blue",
    "hex": "#1E5AA8",
    "imageUrl": "https://via.placeholder.com/80/1E5AA8/FFFFFF?text=Blue",
    "swatchImageUrl": "https://via.placeholder.com/80/1E5AA8/FFFFFF?text=Blue",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-024",
    "sku": "RHSS-024",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Royal",
    "color_name": "Royal",
    "colorFamily": "Blue",
    "hex": "#243D9C",
    "imageUrl": "https://via.placeholder.com/80/243D9C/FFFFFF?text=Royal",
    "swatchImageUrl": "https://via.placeholder.com/80/243D9C/FFFFFF?text=Royal",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-025",
    "sku": "RHSS-025",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Soft Navy",
    "color_name": "Soft Navy",
    "colorFamily": "Blue",
    "hex": "#1D2E5C",
    "imageUrl": "https://via.placeholder.com/80/1D2E5C/FFFFFF?text=Navy",
    "swatchImageUrl": "https://via.placeholder.com/80/1D2E5C/FFFFFF?text=Navy",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-026",
    "sku": "RHSS-026",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Lavender",
    "color_name": "Lavender",
    "colorFamily": "Purple",
    "hex": "#B69AD7",
    "imageUrl": "https://via.placeholder.com/80/B69AD7/000000?text=Lavender",
    "swatchImageUrl": "https://via.placeholder.com/80/B69AD7/000000?text=Lavender",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-027",
    "sku": "RHSS-027",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Amethyst",
    "color_name": "Amethyst",
    "colorFamily": "Purple",
    "hex": "#7E57B8",
    "imageUrl": "https://via.placeholder.com/80/7E57B8/FFFFFF?text=Amethyst",
    "swatchImageUrl": "https://via.placeholder.com/80/7E57B8/FFFFFF?text=Amethyst",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-028",
    "sku": "RHSS-028",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Medium Purple",
    "color_name": "Medium Purple",
    "colorFamily": "Purple",
    "hex": "#673AB7",
    "imageUrl": "https://via.placeholder.com/80/673AB7/FFFFFF?text=Purple",
    "swatchImageUrl": "https://via.placeholder.com/80/673AB7/FFFFFF?text=Purple",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-029",
    "sku": "RHSS-029",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Cafe Latte",
    "color_name": "Cafe Latte",
    "colorFamily": "Brown",
    "hex": "#A78160",
    "imageUrl": "https://via.placeholder.com/80/A78160/FFFFFF?text=Latte",
    "swatchImageUrl": "https://via.placeholder.com/80/A78160/FFFFFF?text=Latte",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "RHSS-030",
    "sku": "RHSS-030",
    "brand": "Red Heart Super Saver",
    "line": "Solid",
    "colorName": "Coffee",
    "color_name": "Coffee",
    "colorFamily": "Brown",
    "hex": "#5A3825",
    "imageUrl": "https://via.placeholder.com/80/5A3825/FFFFFF?text=Coffee",
    "swatchImageUrl": "https://via.placeholder.com/80/5A3825/FFFFFF?text=Coffee",
    "sourceUrl": "https://www.yarnspirations.com/collections/red-heart-super-saver-yarn",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-001",
    "sku": "ILTY-001",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "White",
    "color_name": "White",
    "colorFamily": "Neutral",
    "hex": "#FFFFFF",
    "imageUrl": "https://via.placeholder.com/80/FFFFFF/000000?text=White",
    "swatchImageUrl": "https://via.placeholder.com/80/FFFFFF/000000?text=White",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-002",
    "sku": "ILTY-002",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "Ivory",
    "color_name": "Ivory",
    "colorFamily": "Neutral",
    "hex": "#F6EBD2",
    "imageUrl": "https://via.placeholder.com/80/F6EBD2/000000?text=Ivory",
    "swatchImageUrl": "https://via.placeholder.com/80/F6EBD2/000000?text=Ivory",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-003",
    "sku": "ILTY-003",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "Black",
    "color_name": "Black",
    "colorFamily": "Neutral",
    "hex": "#111111",
    "imageUrl": "https://via.placeholder.com/80/111111/FFFFFF?text=Black",
    "swatchImageUrl": "https://via.placeholder.com/80/111111/FFFFFF?text=Black",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-004",
    "sku": "ILTY-004",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "Red",
    "color_name": "Red",
    "colorFamily": "Red",
    "hex": "#C9282D",
    "imageUrl": "https://via.placeholder.com/80/C9282D/FFFFFF?text=Red",
    "swatchImageUrl": "https://via.placeholder.com/80/C9282D/FFFFFF?text=Red",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-005",
    "sku": "ILTY-005",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "Cranberry",
    "color_name": "Cranberry",
    "colorFamily": "Red",
    "hex": "#8A1D2C",
    "imageUrl": "https://via.placeholder.com/80/8A1D2C/FFFFFF?text=Cranberry",
    "swatchImageUrl": "https://via.placeholder.com/80/8A1D2C/FFFFFF?text=Cranberry",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-006",
    "sku": "ILTY-006",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "Aubergine",
    "color_name": "Aubergine",
    "colorFamily": "Purple",
    "hex": "#4B223E",
    "imageUrl": "https://via.placeholder.com/80/4B223E/FFFFFF?text=Aubergine",
    "swatchImageUrl": "https://via.placeholder.com/80/4B223E/FFFFFF?text=Aubergine",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-007",
    "sku": "ILTY-007",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "Soft Blue",
    "color_name": "Soft Blue",
    "colorFamily": "Blue",
    "hex": "#9BC7E4",
    "imageUrl": "https://via.placeholder.com/80/9BC7E4/000000?text=Soft+Blue",
    "swatchImageUrl": "https://via.placeholder.com/80/9BC7E4/000000?text=Soft+Blue",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-008",
    "sku": "ILTY-008",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "Royal",
    "color_name": "Royal",
    "colorFamily": "Blue",
    "hex": "#2446A6",
    "imageUrl": "https://via.placeholder.com/80/2446A6/FFFFFF?text=Royal",
    "swatchImageUrl": "https://via.placeholder.com/80/2446A6/FFFFFF?text=Royal",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-009",
    "sku": "ILTY-009",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "Navy",
    "color_name": "Navy",
    "colorFamily": "Blue",
    "hex": "#1B2B57",
    "imageUrl": "https://via.placeholder.com/80/1B2B57/FFFFFF?text=Navy",
    "swatchImageUrl": "https://via.placeholder.com/80/1B2B57/FFFFFF?text=Navy",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-010",
    "sku": "ILTY-010",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "Pink",
    "color_name": "Pink",
    "colorFamily": "Pink",
    "hex": "#F27AA7",
    "imageUrl": "https://via.placeholder.com/80/F27AA7/000000?text=Pink",
    "swatchImageUrl": "https://via.placeholder.com/80/F27AA7/000000?text=Pink",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-011",
    "sku": "ILTY-011",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "Turquoise",
    "color_name": "Turquoise",
    "colorFamily": "Blue",
    "hex": "#00A7B5",
    "imageUrl": "https://via.placeholder.com/80/00A7B5/FFFFFF?text=Turquoise",
    "swatchImageUrl": "https://via.placeholder.com/80/00A7B5/FFFFFF?text=Turquoise",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-012",
    "sku": "ILTY-012",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "Hot Orchid",
    "color_name": "Hot Orchid",
    "colorFamily": "Pink",
    "hex": "#C2188E",
    "imageUrl": "https://via.placeholder.com/80/C2188E/FFFFFF?text=Orchid",
    "swatchImageUrl": "https://via.placeholder.com/80/C2188E/FFFFFF?text=Orchid",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-013",
    "sku": "ILTY-013",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "Ocean",
    "color_name": "Ocean",
    "colorFamily": "Blue",
    "hex": "#007C89",
    "imageUrl": "https://via.placeholder.com/80/007C89/FFFFFF?text=Ocean",
    "swatchImageUrl": "https://via.placeholder.com/80/007C89/FFFFFF?text=Ocean",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-014",
    "sku": "ILTY-014",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "Mango",
    "color_name": "Mango",
    "colorFamily": "Orange",
    "hex": "#F08A24",
    "imageUrl": "https://via.placeholder.com/80/F08A24/000000?text=Mango",
    "swatchImageUrl": "https://via.placeholder.com/80/F08A24/000000?text=Mango",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-015",
    "sku": "ILTY-015",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "Medium Blue",
    "color_name": "Medium Blue",
    "colorFamily": "Blue",
    "hex": "#3366B8",
    "imageUrl": "https://via.placeholder.com/80/3366B8/FFFFFF?text=Med+Blue",
    "swatchImageUrl": "https://via.placeholder.com/80/3366B8/FFFFFF?text=Med+Blue",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-016",
    "sku": "ILTY-016",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "Dark Olive",
    "color_name": "Dark Olive",
    "colorFamily": "Green",
    "hex": "#4D5D32",
    "imageUrl": "https://via.placeholder.com/80/4D5D32/FFFFFF?text=Olive",
    "swatchImageUrl": "https://via.placeholder.com/80/4D5D32/FFFFFF?text=Olive",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-017",
    "sku": "ILTY-017",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "Brown",
    "color_name": "Brown",
    "colorFamily": "Brown",
    "hex": "#6B4528",
    "imageUrl": "https://via.placeholder.com/80/6B4528/FFFFFF?text=Brown",
    "swatchImageUrl": "https://via.placeholder.com/80/6B4528/FFFFFF?text=Brown",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  },
  {
    "id": "ILTY-018",
    "sku": "ILTY-018",
    "brand": "I Love This Yarn",
    "line": "Solid",
    "colorName": "Forest Green",
    "color_name": "Forest Green",
    "colorFamily": "Green",
    "hex": "#264A34",
    "imageUrl": "https://via.placeholder.com/80/264A34/FFFFFF?text=Forest",
    "swatchImageUrl": "https://via.placeholder.com/80/264A34/FFFFFF?text=Forest",
    "sourceUrl": "https://www.hobbylobby.com/yarn-needle-art/yarn-tools/yarn/i-love-this-yarn/p/yn20120",
    "weight": "4 - Medium/Worsted",
    "fiber": "Acrylic",
    "barcode": "",
    "quantity": 0,
    "reorderLevel": 2,
    "active": true,
    "notes": "Starter row; add barcode later"
  }
] as const

